<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXiGSWqZ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXiGSWqZ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXiGSWqZ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXiGSWqZ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXiGSWqZ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XiGSWqZ',
    'container.build_id' => 'adbe356f',
    'container.build_time' => 1539539334,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXiGSWqZ');
