<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTfskeQl\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTfskeQl/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTfskeQl.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTfskeQl\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTfskeQl\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'TfskeQl',
    'container.build_id' => 'd9817eb3',
    'container.build_time' => 1540200173,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTfskeQl');
